version: '3.7'
services:
  database:
    env_file: .env
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/db
    network_mode: host
  app:
    depends_on:
      - database
    build: .
    container_name: ${APP_CONTAINER_NAME}
    command: sh -c "npm run db:migrate && npm run db:seed && npm run start"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
    network_mode: host
volumes:
  pgdata:
    driver: local
